/**
 * Configuration dynamique des comptes professionnels.
 * Modifiable ici pour ajouter de nouveaux types sans toucher au frontend.
 */
export const PROFESSIONAL_ACCOUNT_TYPES = [
  {
    id: 'artist',
    label: 'Compte Artiste',
    shortLabel: 'Artiste',
    description: 'Publiez votre musique, gérez votre profil et connectez-vous à votre audience.',
    icon: 'mic',
    color: '#1DB954',
    appUrl: process.env.ARTIST_APP_URL || 'http://localhost:5175',
    port: 5175,
    features: [
      'Upload de singles et albums',
      'Profil artiste vérifié',
      'Statistiques d\'écoute en temps réel',
      'Gestion des concerts et billetterie',
    ],
    formFields: [
      { name: 'artist_name', label: 'Nom de scène', type: 'text', required: true },
      { name: 'real_name', label: 'Nom réel', type: 'text', required: true },
      { name: 'email', label: 'Email', type: 'email', required: true },
      { name: 'phone', label: 'Téléphone', type: 'tel', required: true },
      { name: 'identity_document', label: 'Pièce d\'identité', type: 'file', required: true },
      { name: 'facebook_url', label: 'Facebook', type: 'url', required: false, group: 'social' },
      { name: 'instagram_url', label: 'Instagram', type: 'url', required: false, group: 'social' },
      { name: 'twitter_url', label: 'Twitter / X', type: 'url', required: false, group: 'social' },
      { name: 'youtube_url', label: 'YouTube', type: 'url', required: false, group: 'social' },
      { name: 'spotify_url', label: 'Spotify', type: 'url', required: false, group: 'social' },
      { name: 'bio', label: 'Biographie', type: 'textarea', required: false },
    ],
    socialMinRequired: 2,
    applicationEndpoint: '/api/artist-applications',
    statusEndpoint: '/api/artist-applications/my-application',
  },
  {
    id: 'producer',
    label: 'Compte Producteur',
    shortLabel: 'Producteur',
    description: 'Produisez, mixez et collaborez avec des artistes sur la plateforme.',
    icon: 'sliders',
    color: '#8b5cf6',
    appUrl: process.env.PRODUCER_APP_URL || 'http://localhost:5176',
    port: 5176,
    features: [
      'Portfolio de productions',
      'Collaboration avec artistes',
      'Gestion de catalogues audio',
      'Statistiques de production',
    ],
    formFields: [
      { name: 'company_name', label: 'Nom du studio / label', type: 'text', required: true },
      { name: 'real_name', label: 'Nom complet', type: 'text', required: true },
      { name: 'email', label: 'Email professionnel', type: 'email', required: true },
      { name: 'phone', label: 'Téléphone', type: 'tel', required: true },
      { name: 'identity_document', label: 'Pièce d\'identité', type: 'file', required: true },
      { name: 'studio_address', label: 'Adresse du studio', type: 'text', required: true },
      { name: 'years_experience', label: 'Années d\'expérience', type: 'number', required: true },
      { name: 'portfolio_url', label: 'Portfolio / démo reel', type: 'url', required: true },
      { name: 'linkedin_url', label: 'LinkedIn', type: 'url', required: false },
      { name: 'website_url', label: 'Site web', type: 'url', required: false },
      { name: 'bio', label: 'Présentation', type: 'textarea', required: false },
    ],
    applicationEndpoint: '/api/producer-applications',
    statusEndpoint: '/api/producer-applications/my-application',
  },
  {
    id: 'distributor',
    label: 'Compte Distributeur',
    shortLabel: 'Distributeur',
    description: 'Distribuez des catalogues musicaux et gérez les droits sur plusieurs territoires.',
    icon: 'globe',
    color: '#F9A825',
    appUrl: process.env.DISTRIBUTOR_APP_URL || 'http://localhost:5177',
    port: 5177,
    features: [
      'Distribution multi-territoires',
      'Gestion de droits numériques',
      'Rapports de royalties',
      'Catalogue centralisé',
    ],
    formFields: [
      { name: 'company_name', label: 'Nom de l\'entreprise', type: 'text', required: true },
      { name: 'real_name', label: 'Représentant légal', type: 'text', required: true },
      { name: 'email', label: 'Email professionnel', type: 'email', required: true },
      { name: 'phone', label: 'Téléphone', type: 'tel', required: true },
      { name: 'identity_document', label: 'Pièce d\'identité / RCCM', type: 'file', required: true },
      { name: 'business_registration', label: 'Numéro RCCM / enregistrement', type: 'text', required: true },
      { name: 'distribution_territories', label: 'Territoires de distribution', type: 'text', required: true, placeholder: 'Ex: RDC, Afrique centrale, Monde' },
      { name: 'catalog_size', label: 'Taille du catalogue (titres)', type: 'number', required: true },
      { name: 'website_url', label: 'Site web', type: 'url', required: false },
      { name: 'linkedin_url', label: 'LinkedIn', type: 'url', required: false },
      { name: 'bio', label: 'Description de l\'activité', type: 'textarea', required: false },
    ],
    applicationEndpoint: '/api/distributor-applications',
    statusEndpoint: '/api/distributor-applications/my-application',
  },
];

export function getAccountTypeById(id) {
  return PROFESSIONAL_ACCOUNT_TYPES.find((t) => t.id === id) || null;
}
